- hosts: master01
  become: yes
  gather_facts: false
  tasks:
  - name: get join command
    shell: /usr/bin/kubeadm token create --print-join-command
    register: join_command_raw

  - name: set join command
    set_fact:
      join_command: "{{ join_command_raw.stdout_lines[0] }}"

- hosts: worker-nodes
  become: yes
  tasks:
  - name: join cluster
    shell: "{{ hostvars['dommaster01'].join_command }} > ./node-join_$(date +%F_%T).log"

- hosts: master-nodes
  become: yes
  tasks:
  - name: delete admin.conf from remote
    file:
      path: /etc/kubernetes/admin.conf
      state: absent
