apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
  labels:
    app: ingress-nginx
spec:
  selector:
    matchLabels:
      app: ingress-nginx
  template:
    metadata:
      labels:
        app: ingress-nginx
    spec:
      serviceAccountName: ingress-nginx
      terminationGracePeriodSeconds: 30
      nodeSelector:
        beta.kubernetes.io/os: linux
      containers:
      - name: ingress-nginx
        image: nginx/nginx-ingress:1.5.8-alpine
        imagePullPolicy: Always
        args:
        - -nginx-plus=false
        - -nginx-configmaps=$(POD_NAMESPACE)/ingress-nginx
        - -default-server-tls-secret=$(POD_NAMESPACE)/nginx-tls
        - -ingress-class=nginx
        - -use-ingress-class-only=false
        - -health-status=false
        - -nginx-debug=false
        - -v=1
        - -nginx-status=true
        - -nginx-status-port=8080
        - -nginx-status-allow-cidrs=127.0.0.1
        - -report-ingress-status
        - -enable-leader-election=true
        - -leader-election-lock-name=ingress-nginx-leader-election
        - -wildcard-tls-secret=$(POD_NAMESPACE)/nginx-tls
        - -enable-custom-resources=false
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - name: http
          containerPort: 80
          hostPort: 80
        - name: https
          containerPort: 443
          hostPort: 443
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi