apiVersion: v1
kind: Secret
metadata:
  name: nginx-tls
  namespace: ingress-nginx
  labels:
    app: ingress-nginx
data:
  tls.crt: 
  tls.key: 

# You can create your own secret and with command (kubectl create secret generic gitlab-secret --from-file=tls.crt=/path/to/file --from-file=tls.key=path/to file) after cluter bootstrapped 
